---
title: Kalina Suter Aerial Artist
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kalinasuter@gmail.com
description: Aerialist dancer creation
baseurl: 
url: http://kalinasuter.com
instagram_username: inkedleaf
markdown: kramdown
exclude:
- node_modules
- package.json
