---
title: Kalina Suter Aerial Artist
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
published: false
email: kalinasuter@gmail.com
description: A seabird and wolf child at heart, Kalina draws upon her instinctive
  nature in her creative style and movement. Kalina’s main passion and specialty is
  Dance Trapeze, her other skills included Lyra (duo and solo), aerial fabric, and
  corde lisse.
baseurl: 
url: http://kalinasuter.com
instagram_username: inkedleaf
markdown: kramdown
exclude:
- node_modules
- package.json
